# Generated by Django 4.1.7 on 2023-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(default=20, verbose_name="Age"),
        ),
    ]
