# Generated by Django 4.1.7 on 2023-03-20 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Country",
        ),
    ]
